sudo: required

services:
  - docker

before_install:
  - docker build -t nacho270/docker-react-course -f Dockerfile.dev .

script:
  - docker run -e CI=true nacho270/docker-react-course npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react-course"
  env: "DockerReactCourse-env"
  bucket_name: "elasticbeanstalk-eu-west-2-063131236371"
  bucket_path: "docker-react-course"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
