sudo: required

services:
  - docker

before_install:
  - docker build -t nacho270/docker-react-course -f Dockerfile.dev .

script:
  - docker run -e CI=true nacho270/docker-react-course npm run test
